### ISSUE TITLE
Error in iOS simulator, goes away during 'Debug JS Remotely'

### ISSUE THREAD

**Issue by jaredmharris** [longseespace/react-native-hammerjs#5]
Getting the following error when trying to implement the swipe-view.js example in my project.
https://github.com/longseespace/react-native-hammerjs/blob/master/ReactNativeHammerJSExample/src/swipe-view.js

![screen shot 2017-01-09 at 7 17 06 pm](https://cloud.githubusercontent.com/assets/1580419/21789062/350125fe-d6a0-11e6-8d66-fd700cd1c1ca.png)

As soon as I click on the image in the simulator the error is thrown. If I enable 'Debug JS Remotely' in the Apple Simulator App then the app works and I can click and drag the image in the simulator to simulate a swipe. Any ideas why this would happen?

**Comment by jaredmharris** [comment]
Here are my dependencies if that matters:

"dependencies": {
    "react": "15.4.1",
    "react-native": "^0.40.0",
    "react-native-hammerjs": "^2.0.9"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.0.0",
    "react-test-renderer": "15.4.1"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by longseespace** [comment]
@jaredmharris I can't seem to reproduce in my local machine. Can you try `react-native` v0.39.2 and master branch of `react-native-hammerjs`?

**Comment by jaredmharris** [comment]
@longseespace I copied in the master branch into my ./node_module/react-native-hammerjs dir and it worked. It worked with both react native 39.2 and 40.0. So looks like the issue is something in the npm installation. Any chance the npm release can be updated?

**Comment by longseespace** [comment]
@jaredmharris Actually there was a bug in `v2.0.9` that I fixed on master. Will release new version soon :)

**Comment by jaredmharris** [comment]
@longseespace woohoo! thanks!

**Comment by longseespace** [comment]
@jaredmharris Just published `v2.0.11`, try if it work for you

**Comment by longseespace** [comment]
I'm closing the issue now. Feel free to reopen if it doesn't work for you
